<?php
/**
 * ClientApi
 * PHP version 5
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evolia
 *
 * Connection of Troops & Evolia
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Evolia\SDK;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Evolia\ApiException;
use Evolia\Configuration;
use Evolia\HeaderSelector;
use Evolia\ObjectSerializer;

/**
 * ClientApi Class Doc Comment
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ClientApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation searchClient
     *
     * This endpoint is used to search the siret in the DB from the NIC and the Siret
     *
     * @param  string $authorization authorization (required)
     * @param  string $registrationNumber registrationNumber (required)
     * @param  string $agencyId agencyId (required)
     *
     * @throws \Evolia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Evolia\Model\SiretQueryResult[]
     */
    public function searchClient($authorization, $registrationNumber, $agencyId)
    {
        list($response) = $this->searchClientWithHttpInfo($authorization, $registrationNumber, $agencyId);
        return $response;
    }

    /**
     * Operation searchClientWithHttpInfo
     *
     * This endpoint is used to search the siret in the DB from the NIC and the Siret
     *
     * @param  string $authorization (required)
     * @param  string $registrationNumber (required)
     * @param  string $agencyId (required)
     *
     * @throws \Evolia\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Evolia\Model\SiretQueryResult[], HTTP status code, HTTP response headers (array of strings)
     */
    public function searchClientWithHttpInfo($authorization, $registrationNumber, $agencyId)
    {
        $returnType = '\Evolia\Model\SiretQueryResult[]';
        $request = $this->searchClientRequest($authorization, $registrationNumber, $agencyId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Evolia\Model\SiretQueryResult[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchClientAsync
     *
     * This endpoint is used to search the siret in the DB from the NIC and the Siret
     *
     * @param  string $authorization (required)
     * @param  string $registrationNumber (required)
     * @param  string $agencyId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchClientAsync($authorization, $registrationNumber, $agencyId)
    {
        return $this->searchClientAsyncWithHttpInfo($authorization, $registrationNumber, $agencyId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchClientAsyncWithHttpInfo
     *
     * This endpoint is used to search the siret in the DB from the NIC and the Siret
     *
     * @param  string $authorization (required)
     * @param  string $registrationNumber (required)
     * @param  string $agencyId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchClientAsyncWithHttpInfo($authorization, $registrationNumber, $agencyId)
    {
        $returnType = '\Evolia\Model\SiretQueryResult[]';
        $request = $this->searchClientRequest($authorization, $registrationNumber, $agencyId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchClient'
     *
     * @param  string $authorization (required)
     * @param  string $registrationNumber (required)
     * @param  string $agencyId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function searchClientRequest($authorization, $registrationNumber, $agencyId)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling searchClient'
            );
        }
        // verify the required parameter 'registrationNumber' is set
        if ($registrationNumber === null || (is_array($registrationNumber) && count($registrationNumber) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $registrationNumber when calling searchClient'
            );
        }
        // verify the required parameter 'agencyId' is set
        if ($agencyId === null || (is_array($agencyId) && count($agencyId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $agencyId when calling searchClient'
            );
        }

        $resourcePath = '/api/v3/client/{registrationNumber}/{agencyId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($registrationNumber !== null) {
            $resourcePath = str_replace(
                '{' . 'registrationNumber' . '}',
                ObjectSerializer::toPathValue($registrationNumber),
                $resourcePath
            );
        }
        // path params
        if ($agencyId !== null) {
            $resourcePath = str_replace(
                '{' . 'agencyId' . '}',
                ObjectSerializer::toPathValue($agencyId),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
