<?php
/**
 * Contract
 *
 * PHP version 5
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evolia
 *
 * Connection of Troops & Evolia
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Evolia\Model;

use \ArrayAccess;
use \Evolia\ObjectSerializer;

/**
 * Contract Class Doc Comment
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Contract implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Contract';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'idContrat' => 'int',
'idPersonne' => 'int',
'idClient' => 'int',
'codeMission' => 'string',
'ordreClient' => 'int',
'lieuxdeMission' => '\Evolia\Model\LieuxdeMission',
'rubriquesContractuelles' => '\Evolia\Model\PayrollElement[]',
'designation' => 'string',
'adresse1' => 'string',
'adresse2' => 'string',
'adresse3' => 'string',
'cP' => 'string',
'commune' => 'string',
'insee' => 'string',
'pays' => 'string',
'telephone' => 'string',
'fax' => 'string',
'email' => 'string',
'aPE' => 'string',
'tVAPays' => 'string',
'tVAClef' => 'string',
'sIREN' => 'string',
'nIC' => 'string',
'referenceAnalytique' => 'string',
'agence' => 'string',
'debut' => 'string',
'finPrevue' => 'string',
'finReelle' => 'string',
'dateCreation' => 'string',
'categorieSalariale' => 'string',
'motifEmbauche' => 'string',
'justification' => 'string',
'missionARisqueL23131' => 'bool',
'finDeMission' => 'string',
'heureDePresentation' => 'string',
'contractOrder' => 'int',
'typeContrat' => 'int',
'dateEffet' => 'string',
'dateFinAvenant' => 'string',
'souplesseDebut' => 'string',
'souplesseFin' => 'string',
'horairesParticulier' => 'string',
'retourSignatureInterimaire' => 'bool',
'retourSignatureClient' => 'bool',
'tauxPaye' => 'double',
'tauxFacture' => 'double',
'lotFacture' => 'string',
'dureeHebdo' => 'string',
'horaireCollectifMoyen' => 'string',
'idMetier' => 'int',
'metier' => 'string',
'poste' => 'string',
'seuilEtDecompte' => 'string',
'salaireReference1' => 'string',
'description1' => 'string',
'risque1' => 'string',
'moyenAcces' => 'string',
'periodeFermeture' => 'string',
'libelleMetier' => 'string',
'codePCS' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'idContrat' => null,
'idPersonne' => null,
'idClient' => null,
'codeMission' => null,
'ordreClient' => null,
'lieuxdeMission' => null,
'rubriquesContractuelles' => null,
'designation' => null,
'adresse1' => null,
'adresse2' => null,
'adresse3' => null,
'cP' => null,
'commune' => null,
'insee' => null,
'pays' => null,
'telephone' => null,
'fax' => null,
'email' => null,
'aPE' => null,
'tVAPays' => null,
'tVAClef' => null,
'sIREN' => null,
'nIC' => null,
'referenceAnalytique' => null,
'agence' => null,
'debut' => null,
'finPrevue' => null,
'finReelle' => null,
'dateCreation' => null,
'categorieSalariale' => null,
'motifEmbauche' => null,
'justification' => null,
'missionARisqueL23131' => null,
'finDeMission' => null,
'heureDePresentation' => null,
'contractOrder' => null,
'typeContrat' => null,
'dateEffet' => null,
'dateFinAvenant' => null,
'souplesseDebut' => null,
'souplesseFin' => null,
'horairesParticulier' => null,
'retourSignatureInterimaire' => null,
'retourSignatureClient' => null,
'tauxPaye' => 'double',
'tauxFacture' => 'double',
'lotFacture' => null,
'dureeHebdo' => null,
'horaireCollectifMoyen' => null,
'idMetier' => null,
'metier' => null,
'poste' => null,
'seuilEtDecompte' => null,
'salaireReference1' => null,
'description1' => null,
'risque1' => null,
'moyenAcces' => null,
'periodeFermeture' => null,
'libelleMetier' => null,
'codePCS' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'idContrat' => 'IdContrat',
'idPersonne' => 'IdPersonne',
'idClient' => 'IdClient',
'codeMission' => 'CodeMission',
'ordreClient' => 'OrdreClient',
'lieuxdeMission' => 'LieuxdeMission',
'rubriquesContractuelles' => 'RubriquesContractuelles',
'designation' => 'Designation',
'adresse1' => 'Adresse1',
'adresse2' => 'Adresse2',
'adresse3' => 'Adresse3',
'cP' => 'CP',
'commune' => 'Commune',
'insee' => 'Insee',
'pays' => 'Pays',
'telephone' => 'Telephone',
'fax' => 'Fax',
'email' => 'Email',
'aPE' => 'APE',
'tVAPays' => 'TVAPays',
'tVAClef' => 'TVAClef',
'sIREN' => 'SIREN',
'nIC' => 'NIC',
'referenceAnalytique' => 'ReferenceAnalytique',
'agence' => 'Agence',
'debut' => 'Debut',
'finPrevue' => 'FinPrevue',
'finReelle' => 'FinReelle',
'dateCreation' => 'DateCreation',
'categorieSalariale' => 'CategorieSalariale',
'motifEmbauche' => 'MotifEmbauche',
'justification' => 'justification',
'missionARisqueL23131' => 'MissionARisqueL23131',
'finDeMission' => 'FinDeMission',
'heureDePresentation' => 'HeureDePresentation',
'contractOrder' => 'ContractOrder',
'typeContrat' => 'TypeContrat',
'dateEffet' => 'DateEffet',
'dateFinAvenant' => 'DateFinAvenant',
'souplesseDebut' => 'SouplesseDebut',
'souplesseFin' => 'SouplesseFin',
'horairesParticulier' => 'HorairesParticulier',
'retourSignatureInterimaire' => 'RetourSignatureInterimaire',
'retourSignatureClient' => 'RetourSignatureClient',
'tauxPaye' => 'TauxPaye',
'tauxFacture' => 'TauxFacture',
'lotFacture' => 'LotFacture',
'dureeHebdo' => 'DureeHebdo',
'horaireCollectifMoyen' => 'HoraireCollectifMoyen',
'idMetier' => 'IdMetier',
'metier' => 'Metier',
'poste' => 'Poste',
'seuilEtDecompte' => 'SeuilEtDecompte',
'salaireReference1' => 'SalaireReference1',
'description1' => 'Description1',
'risque1' => 'Risque1',
'moyenAcces' => 'MoyenAcces',
'periodeFermeture' => 'PeriodeFermeture',
'libelleMetier' => 'LibelleMetier',
'codePCS' => 'CodePCS'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'idContrat' => 'setIdContrat',
'idPersonne' => 'setIdPersonne',
'idClient' => 'setIdClient',
'codeMission' => 'setCodeMission',
'ordreClient' => 'setOrdreClient',
'lieuxdeMission' => 'setLieuxdeMission',
'rubriquesContractuelles' => 'setRubriquesContractuelles',
'designation' => 'setDesignation',
'adresse1' => 'setAdresse1',
'adresse2' => 'setAdresse2',
'adresse3' => 'setAdresse3',
'cP' => 'setCP',
'commune' => 'setCommune',
'insee' => 'setInsee',
'pays' => 'setPays',
'telephone' => 'setTelephone',
'fax' => 'setFax',
'email' => 'setEmail',
'aPE' => 'setAPE',
'tVAPays' => 'setTVAPays',
'tVAClef' => 'setTVAClef',
'sIREN' => 'setSIREN',
'nIC' => 'setNIC',
'referenceAnalytique' => 'setReferenceAnalytique',
'agence' => 'setAgence',
'debut' => 'setDebut',
'finPrevue' => 'setFinPrevue',
'finReelle' => 'setFinReelle',
'dateCreation' => 'setDateCreation',
'categorieSalariale' => 'setCategorieSalariale',
'motifEmbauche' => 'setMotifEmbauche',
'justification' => 'setJustification',
'missionARisqueL23131' => 'setMissionARisqueL23131',
'finDeMission' => 'setFinDeMission',
'heureDePresentation' => 'setHeureDePresentation',
'contractOrder' => 'setContractOrder',
'typeContrat' => 'setTypeContrat',
'dateEffet' => 'setDateEffet',
'dateFinAvenant' => 'setDateFinAvenant',
'souplesseDebut' => 'setSouplesseDebut',
'souplesseFin' => 'setSouplesseFin',
'horairesParticulier' => 'setHorairesParticulier',
'retourSignatureInterimaire' => 'setRetourSignatureInterimaire',
'retourSignatureClient' => 'setRetourSignatureClient',
'tauxPaye' => 'setTauxPaye',
'tauxFacture' => 'setTauxFacture',
'lotFacture' => 'setLotFacture',
'dureeHebdo' => 'setDureeHebdo',
'horaireCollectifMoyen' => 'setHoraireCollectifMoyen',
'idMetier' => 'setIdMetier',
'metier' => 'setMetier',
'poste' => 'setPoste',
'seuilEtDecompte' => 'setSeuilEtDecompte',
'salaireReference1' => 'setSalaireReference1',
'description1' => 'setDescription1',
'risque1' => 'setRisque1',
'moyenAcces' => 'setMoyenAcces',
'periodeFermeture' => 'setPeriodeFermeture',
'libelleMetier' => 'setLibelleMetier',
'codePCS' => 'setCodePCS'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'idContrat' => 'getIdContrat',
'idPersonne' => 'getIdPersonne',
'idClient' => 'getIdClient',
'codeMission' => 'getCodeMission',
'ordreClient' => 'getOrdreClient',
'lieuxdeMission' => 'getLieuxdeMission',
'rubriquesContractuelles' => 'getRubriquesContractuelles',
'designation' => 'getDesignation',
'adresse1' => 'getAdresse1',
'adresse2' => 'getAdresse2',
'adresse3' => 'getAdresse3',
'cP' => 'getCP',
'commune' => 'getCommune',
'insee' => 'getInsee',
'pays' => 'getPays',
'telephone' => 'getTelephone',
'fax' => 'getFax',
'email' => 'getEmail',
'aPE' => 'getAPE',
'tVAPays' => 'getTVAPays',
'tVAClef' => 'getTVAClef',
'sIREN' => 'getSIREN',
'nIC' => 'getNIC',
'referenceAnalytique' => 'getReferenceAnalytique',
'agence' => 'getAgence',
'debut' => 'getDebut',
'finPrevue' => 'getFinPrevue',
'finReelle' => 'getFinReelle',
'dateCreation' => 'getDateCreation',
'categorieSalariale' => 'getCategorieSalariale',
'motifEmbauche' => 'getMotifEmbauche',
'justification' => 'getJustification',
'missionARisqueL23131' => 'getMissionARisqueL23131',
'finDeMission' => 'getFinDeMission',
'heureDePresentation' => 'getHeureDePresentation',
'contractOrder' => 'getContractOrder',
'typeContrat' => 'getTypeContrat',
'dateEffet' => 'getDateEffet',
'dateFinAvenant' => 'getDateFinAvenant',
'souplesseDebut' => 'getSouplesseDebut',
'souplesseFin' => 'getSouplesseFin',
'horairesParticulier' => 'getHorairesParticulier',
'retourSignatureInterimaire' => 'getRetourSignatureInterimaire',
'retourSignatureClient' => 'getRetourSignatureClient',
'tauxPaye' => 'getTauxPaye',
'tauxFacture' => 'getTauxFacture',
'lotFacture' => 'getLotFacture',
'dureeHebdo' => 'getDureeHebdo',
'horaireCollectifMoyen' => 'getHoraireCollectifMoyen',
'idMetier' => 'getIdMetier',
'metier' => 'getMetier',
'poste' => 'getPoste',
'seuilEtDecompte' => 'getSeuilEtDecompte',
'salaireReference1' => 'getSalaireReference1',
'description1' => 'getDescription1',
'risque1' => 'getRisque1',
'moyenAcces' => 'getMoyenAcces',
'periodeFermeture' => 'getPeriodeFermeture',
'libelleMetier' => 'getLibelleMetier',
'codePCS' => 'getCodePCS'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['idContrat'] = isset($data['idContrat']) ? $data['idContrat'] : null;
        $this->container['idPersonne'] = isset($data['idPersonne']) ? $data['idPersonne'] : null;
        $this->container['idClient'] = isset($data['idClient']) ? $data['idClient'] : null;
        $this->container['codeMission'] = isset($data['codeMission']) ? $data['codeMission'] : null;
        $this->container['ordreClient'] = isset($data['ordreClient']) ? $data['ordreClient'] : null;
        $this->container['lieuxdeMission'] = isset($data['lieuxdeMission']) ? $data['lieuxdeMission'] : null;
        $this->container['rubriquesContractuelles'] = isset($data['rubriquesContractuelles']) ? $data['rubriquesContractuelles'] : null;
        $this->container['designation'] = isset($data['designation']) ? $data['designation'] : null;
        $this->container['adresse1'] = isset($data['adresse1']) ? $data['adresse1'] : null;
        $this->container['adresse2'] = isset($data['adresse2']) ? $data['adresse2'] : null;
        $this->container['adresse3'] = isset($data['adresse3']) ? $data['adresse3'] : null;
        $this->container['cP'] = isset($data['cP']) ? $data['cP'] : null;
        $this->container['commune'] = isset($data['commune']) ? $data['commune'] : null;
        $this->container['insee'] = isset($data['insee']) ? $data['insee'] : null;
        $this->container['pays'] = isset($data['pays']) ? $data['pays'] : null;
        $this->container['telephone'] = isset($data['telephone']) ? $data['telephone'] : null;
        $this->container['fax'] = isset($data['fax']) ? $data['fax'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['aPE'] = isset($data['aPE']) ? $data['aPE'] : null;
        $this->container['tVAPays'] = isset($data['tVAPays']) ? $data['tVAPays'] : null;
        $this->container['tVAClef'] = isset($data['tVAClef']) ? $data['tVAClef'] : null;
        $this->container['sIREN'] = isset($data['sIREN']) ? $data['sIREN'] : null;
        $this->container['nIC'] = isset($data['nIC']) ? $data['nIC'] : null;
        $this->container['referenceAnalytique'] = isset($data['referenceAnalytique']) ? $data['referenceAnalytique'] : null;
        $this->container['agence'] = isset($data['agence']) ? $data['agence'] : null;
        $this->container['debut'] = isset($data['debut']) ? $data['debut'] : null;
        $this->container['finPrevue'] = isset($data['finPrevue']) ? $data['finPrevue'] : null;
        $this->container['finReelle'] = isset($data['finReelle']) ? $data['finReelle'] : null;
        $this->container['dateCreation'] = isset($data['dateCreation']) ? $data['dateCreation'] : null;
        $this->container['categorieSalariale'] = isset($data['categorieSalariale']) ? $data['categorieSalariale'] : null;
        $this->container['motifEmbauche'] = isset($data['motifEmbauche']) ? $data['motifEmbauche'] : null;
        $this->container['justification'] = isset($data['justification']) ? $data['justification'] : null;
        $this->container['missionARisqueL23131'] = isset($data['missionARisqueL23131']) ? $data['missionARisqueL23131'] : null;
        $this->container['finDeMission'] = isset($data['finDeMission']) ? $data['finDeMission'] : null;
        $this->container['heureDePresentation'] = isset($data['heureDePresentation']) ? $data['heureDePresentation'] : null;
        $this->container['contractOrder'] = isset($data['contractOrder']) ? $data['contractOrder'] : null;
        $this->container['typeContrat'] = isset($data['typeContrat']) ? $data['typeContrat'] : null;
        $this->container['dateEffet'] = isset($data['dateEffet']) ? $data['dateEffet'] : null;
        $this->container['dateFinAvenant'] = isset($data['dateFinAvenant']) ? $data['dateFinAvenant'] : null;
        $this->container['souplesseDebut'] = isset($data['souplesseDebut']) ? $data['souplesseDebut'] : null;
        $this->container['souplesseFin'] = isset($data['souplesseFin']) ? $data['souplesseFin'] : null;
        $this->container['horairesParticulier'] = isset($data['horairesParticulier']) ? $data['horairesParticulier'] : null;
        $this->container['retourSignatureInterimaire'] = isset($data['retourSignatureInterimaire']) ? $data['retourSignatureInterimaire'] : null;
        $this->container['retourSignatureClient'] = isset($data['retourSignatureClient']) ? $data['retourSignatureClient'] : null;
        $this->container['tauxPaye'] = isset($data['tauxPaye']) ? $data['tauxPaye'] : null;
        $this->container['tauxFacture'] = isset($data['tauxFacture']) ? $data['tauxFacture'] : null;
        $this->container['lotFacture'] = isset($data['lotFacture']) ? $data['lotFacture'] : null;
        $this->container['dureeHebdo'] = isset($data['dureeHebdo']) ? $data['dureeHebdo'] : null;
        $this->container['horaireCollectifMoyen'] = isset($data['horaireCollectifMoyen']) ? $data['horaireCollectifMoyen'] : null;
        $this->container['idMetier'] = isset($data['idMetier']) ? $data['idMetier'] : null;
        $this->container['metier'] = isset($data['metier']) ? $data['metier'] : null;
        $this->container['poste'] = isset($data['poste']) ? $data['poste'] : null;
        $this->container['seuilEtDecompte'] = isset($data['seuilEtDecompte']) ? $data['seuilEtDecompte'] : null;
        $this->container['salaireReference1'] = isset($data['salaireReference1']) ? $data['salaireReference1'] : null;
        $this->container['description1'] = isset($data['description1']) ? $data['description1'] : null;
        $this->container['risque1'] = isset($data['risque1']) ? $data['risque1'] : null;
        $this->container['moyenAcces'] = isset($data['moyenAcces']) ? $data['moyenAcces'] : null;
        $this->container['periodeFermeture'] = isset($data['periodeFermeture']) ? $data['periodeFermeture'] : null;
        $this->container['libelleMetier'] = isset($data['libelleMetier']) ? $data['libelleMetier'] : null;
        $this->container['codePCS'] = isset($data['codePCS']) ? $data['codePCS'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['idContrat'] === null) {
            $invalidProperties[] = "'idContrat' can't be null";
        }
        if ($this->container['idPersonne'] === null) {
            $invalidProperties[] = "'idPersonne' can't be null";
        }
        if ($this->container['idClient'] === null) {
            $invalidProperties[] = "'idClient' can't be null";
        }
        if ($this->container['codeMission'] === null) {
            $invalidProperties[] = "'codeMission' can't be null";
        }
        if ($this->container['ordreClient'] === null) {
            $invalidProperties[] = "'ordreClient' can't be null";
        }
        if ($this->container['designation'] === null) {
            $invalidProperties[] = "'designation' can't be null";
        }
        if ($this->container['adresse1'] === null) {
            $invalidProperties[] = "'adresse1' can't be null";
        }
        if ($this->container['cP'] === null) {
            $invalidProperties[] = "'cP' can't be null";
        }
        if ($this->container['commune'] === null) {
            $invalidProperties[] = "'commune' can't be null";
        }
        if ($this->container['insee'] === null) {
            $invalidProperties[] = "'insee' can't be null";
        }
        if ($this->container['pays'] === null) {
            $invalidProperties[] = "'pays' can't be null";
        }
        if ($this->container['agence'] === null) {
            $invalidProperties[] = "'agence' can't be null";
        }
        if ($this->container['debut'] === null) {
            $invalidProperties[] = "'debut' can't be null";
        }
        if ($this->container['finPrevue'] === null) {
            $invalidProperties[] = "'finPrevue' can't be null";
        }
        if ($this->container['finReelle'] === null) {
            $invalidProperties[] = "'finReelle' can't be null";
        }
        if ($this->container['dateCreation'] === null) {
            $invalidProperties[] = "'dateCreation' can't be null";
        }
        if ($this->container['categorieSalariale'] === null) {
            $invalidProperties[] = "'categorieSalariale' can't be null";
        }
        if ($this->container['motifEmbauche'] === null) {
            $invalidProperties[] = "'motifEmbauche' can't be null";
        }
        if ($this->container['missionARisqueL23131'] === null) {
            $invalidProperties[] = "'missionARisqueL23131' can't be null";
        }
        if ($this->container['finDeMission'] === null) {
            $invalidProperties[] = "'finDeMission' can't be null";
        }
        if ($this->container['heureDePresentation'] === null) {
            $invalidProperties[] = "'heureDePresentation' can't be null";
        }
        if ($this->container['contractOrder'] === null) {
            $invalidProperties[] = "'contractOrder' can't be null";
        }
        if ($this->container['typeContrat'] === null) {
            $invalidProperties[] = "'typeContrat' can't be null";
        }
        if ($this->container['dateEffet'] === null) {
            $invalidProperties[] = "'dateEffet' can't be null";
        }
        if ($this->container['dateFinAvenant'] === null) {
            $invalidProperties[] = "'dateFinAvenant' can't be null";
        }
        if ($this->container['souplesseDebut'] === null) {
            $invalidProperties[] = "'souplesseDebut' can't be null";
        }
        if ($this->container['souplesseFin'] === null) {
            $invalidProperties[] = "'souplesseFin' can't be null";
        }
        if ($this->container['tauxPaye'] === null) {
            $invalidProperties[] = "'tauxPaye' can't be null";
        }
        if ($this->container['tauxFacture'] === null) {
            $invalidProperties[] = "'tauxFacture' can't be null";
        }
        if ($this->container['lotFacture'] === null) {
            $invalidProperties[] = "'lotFacture' can't be null";
        }
        if ($this->container['dureeHebdo'] === null) {
            $invalidProperties[] = "'dureeHebdo' can't be null";
        }
        if ($this->container['horaireCollectifMoyen'] === null) {
            $invalidProperties[] = "'horaireCollectifMoyen' can't be null";
        }
        if ($this->container['idMetier'] === null) {
            $invalidProperties[] = "'idMetier' can't be null";
        }
        if ($this->container['seuilEtDecompte'] === null) {
            $invalidProperties[] = "'seuilEtDecompte' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets idContrat
     *
     * @return int
     */
    public function getIdContrat()
    {
        return $this->container['idContrat'];
    }

    /**
     * Sets idContrat
     *
     * @param int $idContrat idContrat
     *
     * @return $this
     */
    public function setIdContrat($idContrat)
    {
        $this->container['idContrat'] = $idContrat;

        return $this;
    }

    /**
     * Gets idPersonne
     *
     * @return int
     */
    public function getIdPersonne()
    {
        return $this->container['idPersonne'];
    }

    /**
     * Sets idPersonne
     *
     * @param int $idPersonne idPersonne
     *
     * @return $this
     */
    public function setIdPersonne($idPersonne)
    {
        $this->container['idPersonne'] = $idPersonne;

        return $this;
    }

    /**
     * Gets idClient
     *
     * @return int
     */
    public function getIdClient()
    {
        return $this->container['idClient'];
    }

    /**
     * Sets idClient
     *
     * @param int $idClient idClient
     *
     * @return $this
     */
    public function setIdClient($idClient)
    {
        $this->container['idClient'] = $idClient;

        return $this;
    }

    /**
     * Gets codeMission
     *
     * @return string
     */
    public function getCodeMission()
    {
        return $this->container['codeMission'];
    }

    /**
     * Sets codeMission
     *
     * @param string $codeMission codeMission
     *
     * @return $this
     */
    public function setCodeMission($codeMission)
    {
        $this->container['codeMission'] = $codeMission;

        return $this;
    }

    /**
     * Gets ordreClient
     *
     * @return int
     */
    public function getOrdreClient()
    {
        return $this->container['ordreClient'];
    }

    /**
     * Sets ordreClient
     *
     * @param int $ordreClient ordreClient
     *
     * @return $this
     */
    public function setOrdreClient($ordreClient)
    {
        $this->container['ordreClient'] = $ordreClient;

        return $this;
    }

    /**
     * Gets lieuxdeMission
     *
     * @return \Evolia\Model\LieuxdeMission
     */
    public function getLieuxdeMission()
    {
        return $this->container['lieuxdeMission'];
    }

    /**
     * Sets lieuxdeMission
     *
     * @param \Evolia\Model\LieuxdeMission $lieuxdeMission lieuxdeMission
     *
     * @return $this
     */
    public function setLieuxdeMission($lieuxdeMission)
    {
        $this->container['lieuxdeMission'] = $lieuxdeMission;

        return $this;
    }

    /**
     * Gets rubriquesContractuelles
     *
     * @return \Evolia\Model\PayrollElement[]
     */
    public function getRubriquesContractuelles()
    {
        return $this->container['rubriquesContractuelles'];
    }

    /**
     * Sets rubriquesContractuelles
     *
     * @param \Evolia\Model\PayrollElement[] $rubriquesContractuelles rubriquesContractuelles
     *
     * @return $this
     */
    public function setRubriquesContractuelles($rubriquesContractuelles)
    {
        $this->container['rubriquesContractuelles'] = $rubriquesContractuelles;

        return $this;
    }

    /**
     * Gets designation
     *
     * @return string
     */
    public function getDesignation()
    {
        return $this->container['designation'];
    }

    /**
     * Sets designation
     *
     * @param string $designation designation
     *
     * @return $this
     */
    public function setDesignation($designation)
    {
        $this->container['designation'] = $designation;

        return $this;
    }

    /**
     * Gets adresse1
     *
     * @return string
     */
    public function getAdresse1()
    {
        return $this->container['adresse1'];
    }

    /**
     * Sets adresse1
     *
     * @param string $adresse1 adresse1
     *
     * @return $this
     */
    public function setAdresse1($adresse1)
    {
        $this->container['adresse1'] = $adresse1;

        return $this;
    }

    /**
     * Gets adresse2
     *
     * @return string
     */
    public function getAdresse2()
    {
        return $this->container['adresse2'];
    }

    /**
     * Sets adresse2
     *
     * @param string $adresse2 adresse2
     *
     * @return $this
     */
    public function setAdresse2($adresse2)
    {
        $this->container['adresse2'] = $adresse2;

        return $this;
    }

    /**
     * Gets adresse3
     *
     * @return string
     */
    public function getAdresse3()
    {
        return $this->container['adresse3'];
    }

    /**
     * Sets adresse3
     *
     * @param string $adresse3 adresse3
     *
     * @return $this
     */
    public function setAdresse3($adresse3)
    {
        $this->container['adresse3'] = $adresse3;

        return $this;
    }

    /**
     * Gets cP
     *
     * @return string
     */
    public function getCP()
    {
        return $this->container['cP'];
    }

    /**
     * Sets cP
     *
     * @param string $cP cP
     *
     * @return $this
     */
    public function setCP($cP)
    {
        $this->container['cP'] = $cP;

        return $this;
    }

    /**
     * Gets commune
     *
     * @return string
     */
    public function getCommune()
    {
        return $this->container['commune'];
    }

    /**
     * Sets commune
     *
     * @param string $commune commune
     *
     * @return $this
     */
    public function setCommune($commune)
    {
        $this->container['commune'] = $commune;

        return $this;
    }

    /**
     * Gets insee
     *
     * @return string
     */
    public function getInsee()
    {
        return $this->container['insee'];
    }

    /**
     * Sets insee
     *
     * @param string $insee insee
     *
     * @return $this
     */
    public function setInsee($insee)
    {
        $this->container['insee'] = $insee;

        return $this;
    }

    /**
     * Gets pays
     *
     * @return string
     */
    public function getPays()
    {
        return $this->container['pays'];
    }

    /**
     * Sets pays
     *
     * @param string $pays pays
     *
     * @return $this
     */
    public function setPays($pays)
    {
        $this->container['pays'] = $pays;

        return $this;
    }

    /**
     * Gets telephone
     *
     * @return string
     */
    public function getTelephone()
    {
        return $this->container['telephone'];
    }

    /**
     * Sets telephone
     *
     * @param string $telephone telephone
     *
     * @return $this
     */
    public function setTelephone($telephone)
    {
        $this->container['telephone'] = $telephone;

        return $this;
    }

    /**
     * Gets fax
     *
     * @return string
     */
    public function getFax()
    {
        return $this->container['fax'];
    }

    /**
     * Sets fax
     *
     * @param string $fax fax
     *
     * @return $this
     */
    public function setFax($fax)
    {
        $this->container['fax'] = $fax;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets aPE
     *
     * @return string
     */
    public function getAPE()
    {
        return $this->container['aPE'];
    }

    /**
     * Sets aPE
     *
     * @param string $aPE aPE
     *
     * @return $this
     */
    public function setAPE($aPE)
    {
        $this->container['aPE'] = $aPE;

        return $this;
    }

    /**
     * Gets tVAPays
     *
     * @return string
     */
    public function getTVAPays()
    {
        return $this->container['tVAPays'];
    }

    /**
     * Sets tVAPays
     *
     * @param string $tVAPays tVAPays
     *
     * @return $this
     */
    public function setTVAPays($tVAPays)
    {
        $this->container['tVAPays'] = $tVAPays;

        return $this;
    }

    /**
     * Gets tVAClef
     *
     * @return string
     */
    public function getTVAClef()
    {
        return $this->container['tVAClef'];
    }

    /**
     * Sets tVAClef
     *
     * @param string $tVAClef tVAClef
     *
     * @return $this
     */
    public function setTVAClef($tVAClef)
    {
        $this->container['tVAClef'] = $tVAClef;

        return $this;
    }

    /**
     * Gets sIREN
     *
     * @return string
     */
    public function getSIREN()
    {
        return $this->container['sIREN'];
    }

    /**
     * Sets sIREN
     *
     * @param string $sIREN sIREN
     *
     * @return $this
     */
    public function setSIREN($sIREN)
    {
        $this->container['sIREN'] = $sIREN;

        return $this;
    }

    /**
     * Gets nIC
     *
     * @return string
     */
    public function getNIC()
    {
        return $this->container['nIC'];
    }

    /**
     * Sets nIC
     *
     * @param string $nIC nIC
     *
     * @return $this
     */
    public function setNIC($nIC)
    {
        $this->container['nIC'] = $nIC;

        return $this;
    }

    /**
     * Gets referenceAnalytique
     *
     * @return string
     */
    public function getReferenceAnalytique()
    {
        return $this->container['referenceAnalytique'];
    }

    /**
     * Sets referenceAnalytique
     *
     * @param string $referenceAnalytique referenceAnalytique
     *
     * @return $this
     */
    public function setReferenceAnalytique($referenceAnalytique)
    {
        $this->container['referenceAnalytique'] = $referenceAnalytique;

        return $this;
    }

    /**
     * Gets agence
     *
     * @return string
     */
    public function getAgence()
    {
        return $this->container['agence'];
    }

    /**
     * Sets agence
     *
     * @param string $agence agence
     *
     * @return $this
     */
    public function setAgence($agence)
    {
        $this->container['agence'] = $agence;

        return $this;
    }

    /**
     * Gets debut
     *
     * @return string
     */
    public function getDebut()
    {
        return $this->container['debut'];
    }

    /**
     * Sets debut
     *
     * @param string $debut Date. Not using \"date\" format because it does not serialized correctly.
     *
     * @return $this
     */
    public function setDebut($debut)
    {
        $this->container['debut'] = $debut;

        return $this;
    }

    /**
     * Gets finPrevue
     *
     * @return string
     */
    public function getFinPrevue()
    {
        return $this->container['finPrevue'];
    }

    /**
     * Sets finPrevue
     *
     * @param string $finPrevue Date. Not using \"date\" format because it does not serialized correctly.
     *
     * @return $this
     */
    public function setFinPrevue($finPrevue)
    {
        $this->container['finPrevue'] = $finPrevue;

        return $this;
    }

    /**
     * Gets finReelle
     *
     * @return string
     */
    public function getFinReelle()
    {
        return $this->container['finReelle'];
    }

    /**
     * Sets finReelle
     *
     * @param string $finReelle Date. Not using \"date\" format because it does not serialized correctly.
     *
     * @return $this
     */
    public function setFinReelle($finReelle)
    {
        $this->container['finReelle'] = $finReelle;

        return $this;
    }

    /**
     * Gets dateCreation
     *
     * @return string
     */
    public function getDateCreation()
    {
        return $this->container['dateCreation'];
    }

    /**
     * Sets dateCreation
     *
     * @param string $dateCreation Date. Not using \"date\" format because it does not serialized correctly.
     *
     * @return $this
     */
    public function setDateCreation($dateCreation)
    {
        $this->container['dateCreation'] = $dateCreation;

        return $this;
    }

    /**
     * Gets categorieSalariale
     *
     * @return string
     */
    public function getCategorieSalariale()
    {
        return $this->container['categorieSalariale'];
    }

    /**
     * Sets categorieSalariale
     *
     * @param string $categorieSalariale categorieSalariale
     *
     * @return $this
     */
    public function setCategorieSalariale($categorieSalariale)
    {
        $this->container['categorieSalariale'] = $categorieSalariale;

        return $this;
    }

    /**
     * Gets motifEmbauche
     *
     * @return string
     */
    public function getMotifEmbauche()
    {
        return $this->container['motifEmbauche'];
    }

    /**
     * Sets motifEmbauche
     *
     * @param string $motifEmbauche motifEmbauche
     *
     * @return $this
     */
    public function setMotifEmbauche($motifEmbauche)
    {
        $this->container['motifEmbauche'] = $motifEmbauche;

        return $this;
    }

    /**
     * Gets justification
     *
     * @return string
     */
    public function getJustification()
    {
        return $this->container['justification'];
    }

    /**
     * Sets justification
     *
     * @param string $justification justification
     *
     * @return $this
     */
    public function setJustification($justification)
    {
        $this->container['justification'] = $justification;

        return $this;
    }

    /**
     * Gets missionARisqueL23131
     *
     * @return bool
     */
    public function getMissionARisqueL23131()
    {
        return $this->container['missionARisqueL23131'];
    }

    /**
     * Sets missionARisqueL23131
     *
     * @param bool $missionARisqueL23131 missionARisqueL23131
     *
     * @return $this
     */
    public function setMissionARisqueL23131($missionARisqueL23131)
    {
        $this->container['missionARisqueL23131'] = $missionARisqueL23131;

        return $this;
    }

    /**
     * Gets finDeMission
     *
     * @return string
     */
    public function getFinDeMission()
    {
        return $this->container['finDeMission'];
    }

    /**
     * Sets finDeMission
     *
     * @param string $finDeMission Date. Not using \"date\" format because it does not serialized correctly.
     *
     * @return $this
     */
    public function setFinDeMission($finDeMission)
    {
        $this->container['finDeMission'] = $finDeMission;

        return $this;
    }

    /**
     * Gets heureDePresentation
     *
     * @return string
     */
    public function getHeureDePresentation()
    {
        return $this->container['heureDePresentation'];
    }

    /**
     * Sets heureDePresentation
     *
     * @param string $heureDePresentation heureDePresentation
     *
     * @return $this
     */
    public function setHeureDePresentation($heureDePresentation)
    {
        $this->container['heureDePresentation'] = $heureDePresentation;

        return $this;
    }

    /**
     * Gets contractOrder
     *
     * @return int
     */
    public function getContractOrder()
    {
        return $this->container['contractOrder'];
    }

    /**
     * Sets contractOrder
     *
     * @param int $contractOrder contractOrder
     *
     * @return $this
     */
    public function setContractOrder($contractOrder)
    {
        $this->container['contractOrder'] = $contractOrder;

        return $this;
    }

    /**
     * Gets typeContrat
     *
     * @return int
     */
    public function getTypeContrat()
    {
        return $this->container['typeContrat'];
    }

    /**
     * Sets typeContrat
     *
     * @param int $typeContrat typeContrat
     *
     * @return $this
     */
    public function setTypeContrat($typeContrat)
    {
        $this->container['typeContrat'] = $typeContrat;

        return $this;
    }

    /**
     * Gets dateEffet
     *
     * @return string
     */
    public function getDateEffet()
    {
        return $this->container['dateEffet'];
    }

    /**
     * Sets dateEffet
     *
     * @param string $dateEffet Date. Not using \"date\" format because it does not serialized correctly.
     *
     * @return $this
     */
    public function setDateEffet($dateEffet)
    {
        $this->container['dateEffet'] = $dateEffet;

        return $this;
    }

    /**
     * Gets dateFinAvenant
     *
     * @return string
     */
    public function getDateFinAvenant()
    {
        return $this->container['dateFinAvenant'];
    }

    /**
     * Sets dateFinAvenant
     *
     * @param string $dateFinAvenant Date. Not using \"date\" format because it does not serialized correctly.
     *
     * @return $this
     */
    public function setDateFinAvenant($dateFinAvenant)
    {
        $this->container['dateFinAvenant'] = $dateFinAvenant;

        return $this;
    }

    /**
     * Gets souplesseDebut
     *
     * @return string
     */
    public function getSouplesseDebut()
    {
        return $this->container['souplesseDebut'];
    }

    /**
     * Sets souplesseDebut
     *
     * @param string $souplesseDebut Date. Not using \"date\" format because it does not serialized correctly.
     *
     * @return $this
     */
    public function setSouplesseDebut($souplesseDebut)
    {
        $this->container['souplesseDebut'] = $souplesseDebut;

        return $this;
    }

    /**
     * Gets souplesseFin
     *
     * @return string
     */
    public function getSouplesseFin()
    {
        return $this->container['souplesseFin'];
    }

    /**
     * Sets souplesseFin
     *
     * @param string $souplesseFin Date. Not using \"date\" format because it does not serialized correctly.
     *
     * @return $this
     */
    public function setSouplesseFin($souplesseFin)
    {
        $this->container['souplesseFin'] = $souplesseFin;

        return $this;
    }

    /**
     * Gets horairesParticulier
     *
     * @return string
     */
    public function getHorairesParticulier()
    {
        return $this->container['horairesParticulier'];
    }

    /**
     * Sets horairesParticulier
     *
     * @param string $horairesParticulier horairesParticulier
     *
     * @return $this
     */
    public function setHorairesParticulier($horairesParticulier)
    {
        $this->container['horairesParticulier'] = $horairesParticulier;

        return $this;
    }

    /**
     * Gets retourSignatureInterimaire
     *
     * @return bool
     */
    public function getRetourSignatureInterimaire()
    {
        return $this->container['retourSignatureInterimaire'];
    }

    /**
     * Sets retourSignatureInterimaire
     *
     * @param bool $retourSignatureInterimaire retourSignatureInterimaire
     *
     * @return $this
     */
    public function setRetourSignatureInterimaire($retourSignatureInterimaire)
    {
        $this->container['retourSignatureInterimaire'] = $retourSignatureInterimaire;

        return $this;
    }

    /**
     * Gets retourSignatureClient
     *
     * @return bool
     */
    public function getRetourSignatureClient()
    {
        return $this->container['retourSignatureClient'];
    }

    /**
     * Sets retourSignatureClient
     *
     * @param bool $retourSignatureClient retourSignatureClient
     *
     * @return $this
     */
    public function setRetourSignatureClient($retourSignatureClient)
    {
        $this->container['retourSignatureClient'] = $retourSignatureClient;

        return $this;
    }

    /**
     * Gets tauxPaye
     *
     * @return double
     */
    public function getTauxPaye()
    {
        return $this->container['tauxPaye'];
    }

    /**
     * Sets tauxPaye
     *
     * @param double $tauxPaye tauxPaye
     *
     * @return $this
     */
    public function setTauxPaye($tauxPaye)
    {
        $this->container['tauxPaye'] = $tauxPaye;

        return $this;
    }

    /**
     * Gets tauxFacture
     *
     * @return double
     */
    public function getTauxFacture()
    {
        return $this->container['tauxFacture'];
    }

    /**
     * Sets tauxFacture
     *
     * @param double $tauxFacture tauxFacture
     *
     * @return $this
     */
    public function setTauxFacture($tauxFacture)
    {
        $this->container['tauxFacture'] = $tauxFacture;

        return $this;
    }

    /**
     * Gets lotFacture
     *
     * @return string
     */
    public function getLotFacture()
    {
        return $this->container['lotFacture'];
    }

    /**
     * Sets lotFacture
     *
     * @param string $lotFacture lotFacture
     *
     * @return $this
     */
    public function setLotFacture($lotFacture)
    {
        $this->container['lotFacture'] = $lotFacture;

        return $this;
    }

    /**
     * Gets dureeHebdo
     *
     * @return string
     */
    public function getDureeHebdo()
    {
        return $this->container['dureeHebdo'];
    }

    /**
     * Sets dureeHebdo
     *
     * @param string $dureeHebdo dureeHebdo
     *
     * @return $this
     */
    public function setDureeHebdo($dureeHebdo)
    {
        $this->container['dureeHebdo'] = $dureeHebdo;

        return $this;
    }

    /**
     * Gets horaireCollectifMoyen
     *
     * @return string
     */
    public function getHoraireCollectifMoyen()
    {
        return $this->container['horaireCollectifMoyen'];
    }

    /**
     * Sets horaireCollectifMoyen
     *
     * @param string $horaireCollectifMoyen horaireCollectifMoyen
     *
     * @return $this
     */
    public function setHoraireCollectifMoyen($horaireCollectifMoyen)
    {
        $this->container['horaireCollectifMoyen'] = $horaireCollectifMoyen;

        return $this;
    }

    /**
     * Gets idMetier
     *
     * @return int
     */
    public function getIdMetier()
    {
        return $this->container['idMetier'];
    }

    /**
     * Sets idMetier
     *
     * @param int $idMetier idMetier
     *
     * @return $this
     */
    public function setIdMetier($idMetier)
    {
        $this->container['idMetier'] = $idMetier;

        return $this;
    }

    /**
     * Gets metier
     *
     * @return string
     */
    public function getMetier()
    {
        return $this->container['metier'];
    }

    /**
     * Sets metier
     *
     * @param string $metier metier
     *
     * @return $this
     */
    public function setMetier($metier)
    {
        $this->container['metier'] = $metier;

        return $this;
    }

    /**
     * Gets poste
     *
     * @return string
     */
    public function getPoste()
    {
        return $this->container['poste'];
    }

    /**
     * Sets poste
     *
     * @param string $poste poste
     *
     * @return $this
     */
    public function setPoste($poste)
    {
        $this->container['poste'] = $poste;

        return $this;
    }

    /**
     * Gets seuilEtDecompte
     *
     * @return string
     */
    public function getSeuilEtDecompte()
    {
        return $this->container['seuilEtDecompte'];
    }

    /**
     * Sets seuilEtDecompte
     *
     * @param string $seuilEtDecompte seuilEtDecompte
     *
     * @return $this
     */
    public function setSeuilEtDecompte($seuilEtDecompte)
    {
        $this->container['seuilEtDecompte'] = $seuilEtDecompte;

        return $this;
    }

    /**
     * Gets salaireReference1
     *
     * @return string
     */
    public function getSalaireReference1()
    {
        return $this->container['salaireReference1'];
    }

    /**
     * Sets salaireReference1
     *
     * @param string $salaireReference1 salaireReference1
     *
     * @return $this
     */
    public function setSalaireReference1($salaireReference1)
    {
        $this->container['salaireReference1'] = $salaireReference1;

        return $this;
    }

    /**
     * Gets description1
     *
     * @return string
     */
    public function getDescription1()
    {
        return $this->container['description1'];
    }

    /**
     * Sets description1
     *
     * @param string $description1 description1
     *
     * @return $this
     */
    public function setDescription1($description1)
    {
        $this->container['description1'] = $description1;

        return $this;
    }

    /**
     * Gets risque1
     *
     * @return string
     */
    public function getRisque1()
    {
        return $this->container['risque1'];
    }

    /**
     * Sets risque1
     *
     * @param string $risque1 risque1
     *
     * @return $this
     */
    public function setRisque1($risque1)
    {
        $this->container['risque1'] = $risque1;

        return $this;
    }

    /**
     * Gets moyenAcces
     *
     * @return string
     */
    public function getMoyenAcces()
    {
        return $this->container['moyenAcces'];
    }

    /**
     * Sets moyenAcces
     *
     * @param string $moyenAcces moyenAcces
     *
     * @return $this
     */
    public function setMoyenAcces($moyenAcces)
    {
        $this->container['moyenAcces'] = $moyenAcces;

        return $this;
    }

    /**
     * Gets periodeFermeture
     *
     * @return string
     */
    public function getPeriodeFermeture()
    {
        return $this->container['periodeFermeture'];
    }

    /**
     * Sets periodeFermeture
     *
     * @param string $periodeFermeture periodeFermeture
     *
     * @return $this
     */
    public function setPeriodeFermeture($periodeFermeture)
    {
        $this->container['periodeFermeture'] = $periodeFermeture;

        return $this;
    }

    /**
     * Gets libelleMetier
     *
     * @return string
     */
    public function getLibelleMetier()
    {
        return $this->container['libelleMetier'];
    }

    /**
     * Sets libelleMetier
     *
     * @param string $libelleMetier libelleMetier
     *
     * @return $this
     */
    public function setLibelleMetier($libelleMetier)
    {
        $this->container['libelleMetier'] = $libelleMetier;

        return $this;
    }

    /**
     * Gets codePCS
     *
     * @return string
     */
    public function getCodePCS()
    {
        return $this->container['codePCS'];
    }

    /**
     * Sets codePCS
     *
     * @param string $codePCS codePCS
     *
     * @return $this
     */
    public function setCodePCS($codePCS)
    {
        $this->container['codePCS'] = $codePCS;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
