<?php
/**
 * ReferencesResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evolia
 *
 * Connection of Troops & Evolia
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Evolia\Model;

use \ArrayAccess;
use \Evolia\ObjectSerializer;

/**
 * ReferencesResponse Class Doc Comment
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReferencesResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ReferencesResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'bookKeepingVariables' => '\Evolia\Model\ReferenceItem[]',
'payrollItems' => '\Evolia\Model\ReferenceItem[]',
'countries' => '\Evolia\Model\ReferenceItem[]',
'billingTerms' => '\Evolia\Model\ReferenceItem[]',
'employeeStatuses' => '\Evolia\Model\ReferenceItem[]',
'nationalities' => '\Evolia\Model\ReferenceItem[]',
'jobs' => '\Evolia\Model\ReferenceItem[]',
'legalReasons' => '\Evolia\Model\ReferenceItem[]',
'vatRates' => '\Evolia\Model\ReferenceItem[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'bookKeepingVariables' => null,
'payrollItems' => null,
'countries' => null,
'billingTerms' => null,
'employeeStatuses' => null,
'nationalities' => null,
'jobs' => null,
'legalReasons' => null,
'vatRates' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bookKeepingVariables' => 'bookKeepingVariables',
'payrollItems' => 'payrollItems',
'countries' => 'countries',
'billingTerms' => 'billingTerms',
'employeeStatuses' => 'employeeStatuses',
'nationalities' => 'nationalities',
'jobs' => 'jobs',
'legalReasons' => 'legalReasons',
'vatRates' => 'vatRates'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bookKeepingVariables' => 'setBookKeepingVariables',
'payrollItems' => 'setPayrollItems',
'countries' => 'setCountries',
'billingTerms' => 'setBillingTerms',
'employeeStatuses' => 'setEmployeeStatuses',
'nationalities' => 'setNationalities',
'jobs' => 'setJobs',
'legalReasons' => 'setLegalReasons',
'vatRates' => 'setVatRates'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bookKeepingVariables' => 'getBookKeepingVariables',
'payrollItems' => 'getPayrollItems',
'countries' => 'getCountries',
'billingTerms' => 'getBillingTerms',
'employeeStatuses' => 'getEmployeeStatuses',
'nationalities' => 'getNationalities',
'jobs' => 'getJobs',
'legalReasons' => 'getLegalReasons',
'vatRates' => 'getVatRates'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['bookKeepingVariables'] = isset($data['bookKeepingVariables']) ? $data['bookKeepingVariables'] : null;
        $this->container['payrollItems'] = isset($data['payrollItems']) ? $data['payrollItems'] : null;
        $this->container['countries'] = isset($data['countries']) ? $data['countries'] : null;
        $this->container['billingTerms'] = isset($data['billingTerms']) ? $data['billingTerms'] : null;
        $this->container['employeeStatuses'] = isset($data['employeeStatuses']) ? $data['employeeStatuses'] : null;
        $this->container['nationalities'] = isset($data['nationalities']) ? $data['nationalities'] : null;
        $this->container['jobs'] = isset($data['jobs']) ? $data['jobs'] : null;
        $this->container['legalReasons'] = isset($data['legalReasons']) ? $data['legalReasons'] : null;
        $this->container['vatRates'] = isset($data['vatRates']) ? $data['vatRates'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bookKeepingVariables
     *
     * @return \Evolia\Model\ReferenceItem[]
     */
    public function getBookKeepingVariables()
    {
        return $this->container['bookKeepingVariables'];
    }

    /**
     * Sets bookKeepingVariables
     *
     * @param \Evolia\Model\ReferenceItem[] $bookKeepingVariables bookKeepingVariables
     *
     * @return $this
     */
    public function setBookKeepingVariables($bookKeepingVariables)
    {
        $this->container['bookKeepingVariables'] = $bookKeepingVariables;

        return $this;
    }

    /**
     * Gets payrollItems
     *
     * @return \Evolia\Model\ReferenceItem[]
     */
    public function getPayrollItems()
    {
        return $this->container['payrollItems'];
    }

    /**
     * Sets payrollItems
     *
     * @param \Evolia\Model\ReferenceItem[] $payrollItems payrollItems
     *
     * @return $this
     */
    public function setPayrollItems($payrollItems)
    {
        $this->container['payrollItems'] = $payrollItems;

        return $this;
    }

    /**
     * Gets countries
     *
     * @return \Evolia\Model\ReferenceItem[]
     */
    public function getCountries()
    {
        return $this->container['countries'];
    }

    /**
     * Sets countries
     *
     * @param \Evolia\Model\ReferenceItem[] $countries countries
     *
     * @return $this
     */
    public function setCountries($countries)
    {
        $this->container['countries'] = $countries;

        return $this;
    }

    /**
     * Gets billingTerms
     *
     * @return \Evolia\Model\ReferenceItem[]
     */
    public function getBillingTerms()
    {
        return $this->container['billingTerms'];
    }

    /**
     * Sets billingTerms
     *
     * @param \Evolia\Model\ReferenceItem[] $billingTerms billingTerms
     *
     * @return $this
     */
    public function setBillingTerms($billingTerms)
    {
        $this->container['billingTerms'] = $billingTerms;

        return $this;
    }

    /**
     * Gets employeeStatuses
     *
     * @return \Evolia\Model\ReferenceItem[]
     */
    public function getEmployeeStatuses()
    {
        return $this->container['employeeStatuses'];
    }

    /**
     * Sets employeeStatuses
     *
     * @param \Evolia\Model\ReferenceItem[] $employeeStatuses employeeStatuses
     *
     * @return $this
     */
    public function setEmployeeStatuses($employeeStatuses)
    {
        $this->container['employeeStatuses'] = $employeeStatuses;

        return $this;
    }

    /**
     * Gets nationalities
     *
     * @return \Evolia\Model\ReferenceItem[]
     */
    public function getNationalities()
    {
        return $this->container['nationalities'];
    }

    /**
     * Sets nationalities
     *
     * @param \Evolia\Model\ReferenceItem[] $nationalities nationalities
     *
     * @return $this
     */
    public function setNationalities($nationalities)
    {
        $this->container['nationalities'] = $nationalities;

        return $this;
    }

    /**
     * Gets jobs
     *
     * @return \Evolia\Model\ReferenceItem[]
     */
    public function getJobs()
    {
        return $this->container['jobs'];
    }

    /**
     * Sets jobs
     *
     * @param \Evolia\Model\ReferenceItem[] $jobs jobs
     *
     * @return $this
     */
    public function setJobs($jobs)
    {
        $this->container['jobs'] = $jobs;

        return $this;
    }

    /**
     * Gets legalReasons
     *
     * @return \Evolia\Model\ReferenceItem[]
     */
    public function getLegalReasons()
    {
        return $this->container['legalReasons'];
    }

    /**
     * Sets legalReasons
     *
     * @param \Evolia\Model\ReferenceItem[] $legalReasons legalReasons
     *
     * @return $this
     */
    public function setLegalReasons($legalReasons)
    {
        $this->container['legalReasons'] = $legalReasons;

        return $this;
    }

    /**
     * Gets vatRates
     *
     * @return \Evolia\Model\ReferenceItem[]
     */
    public function getVatRates()
    {
        return $this->container['vatRates'];
    }

    /**
     * Sets vatRates
     *
     * @param \Evolia\Model\ReferenceItem[] $vatRates vatRates
     *
     * @return $this
     */
    public function setVatRates($vatRates)
    {
        $this->container['vatRates'] = $vatRates;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
