<?php
/**
 * ResponseErrorOfTimeSheetErrors
 *
 * PHP version 5
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evolia
 *
 * Connection of Troops & Evolia
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Evolia\Model;

use \ArrayAccess;
use \Evolia\ObjectSerializer;

/**
 * ResponseErrorOfTimeSheetErrors Class Doc Comment
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResponseErrorOfTimeSheetErrors implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ResponseErrorOfTimeSheetErrors';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'errorId' => 'string',
'errorText' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'errorId' => null,
'errorText' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'errorId' => 'ErrorId',
'errorText' => 'ErrorText'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'errorId' => 'setErrorId',
'errorText' => 'setErrorText'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'errorId' => 'getErrorId',
'errorText' => 'getErrorText'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const ERROR_ID_SUCCESS = 'Success';
const ERROR_ID_MISSION = 'Mission';
const ERROR_ID_CLIENT = 'Client';
const ERROR_ID_INTERIMAIRE = 'Interimaire';
const ERROR_ID_PAYE = 'Paye';
const ERROR_ID_FACTURE = 'Facture';
const ERROR_ID_DATABASE_ERROR = 'DatabaseError';
const ERROR_ID_CONNEXION_ERROR = 'ConnexionError';
const ERROR_ID_VIDE = 'Vide';
const ERROR_ID_UNKNOWN = 'Unknown';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getErrorIdAllowableValues()
    {
        return [
            self::ERROR_ID_SUCCESS,
self::ERROR_ID_MISSION,
self::ERROR_ID_CLIENT,
self::ERROR_ID_INTERIMAIRE,
self::ERROR_ID_PAYE,
self::ERROR_ID_FACTURE,
self::ERROR_ID_DATABASE_ERROR,
self::ERROR_ID_CONNEXION_ERROR,
self::ERROR_ID_VIDE,
self::ERROR_ID_UNKNOWN,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['errorId'] = isset($data['errorId']) ? $data['errorId'] : null;
        $this->container['errorText'] = isset($data['errorText']) ? $data['errorText'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getErrorIdAllowableValues();
        if (!is_null($this->container['errorId']) && !in_array($this->container['errorId'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'errorId', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets errorId
     *
     * @return string
     */
    public function getErrorId()
    {
        return $this->container['errorId'];
    }

    /**
     * Sets errorId
     *
     * @param string $errorId errorId
     *
     * @return $this
     */
    public function setErrorId($errorId)
    {
        $allowedValues = $this->getErrorIdAllowableValues();
        if (!is_null($errorId) && !in_array($errorId, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'errorId', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['errorId'] = $errorId;

        return $this;
    }

    /**
     * Gets errorText
     *
     * @return string
     */
    public function getErrorText()
    {
        return $this->container['errorText'];
    }

    /**
     * Sets errorText
     *
     * @param string $errorText errorText
     *
     * @return $this
     */
    public function setErrorText($errorText)
    {
        $this->container['errorText'] = $errorText;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
