<?php
/**
 * CandidateAddDpaeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evolia
 *
 * Connection of Troops & Evolia
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Evolia;

/**
 * CandidateAddDpaeTest Class Doc Comment
 *
 * @category    Class
 * @description CandidateAddDpae
 * @package     Evolia
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CandidateAddDpaeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CandidateAddDpae"
     */
    public function testCandidateAddDpae()
    {
    }

    /**
     * Test attribute "refCandidate"
     */
    public function testPropertyRefCandidate()
    {
    }

    /**
     * Test attribute "refMission"
     */
    public function testPropertyRefMission()
    {
    }

    /**
     * Test attribute "agence"
     */
    public function testPropertyAgence()
    {
    }

    /**
     * Test attribute "dateHeurePrevueEmbauche"
     */
    public function testPropertyDateHeurePrevueEmbauche()
    {
    }

    /**
     * Test attribute "numDPAE"
     */
    public function testPropertyNumDPAE()
    {
    }

    /**
     * Test attribute "dateEnvoi"
     */
    public function testPropertyDateEnvoi()
    {
    }
}
