<?php
/**
 * CandidateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evolia
 *
 * Connection of Troops & Evolia
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.10
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Evolia;

/**
 * CandidateTest Class Doc Comment
 *
 * @category    Class
 * @description Candidate
 * @package     Evolia
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CandidateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Candidate"
     */
    public function testCandidate()
    {
    }

    /**
     * Test attribute "titres"
     */
    public function testPropertyTitres()
    {
    }

    /**
     * Test attribute "nom"
     */
    public function testPropertyNom()
    {
    }

    /**
     * Test attribute "preNom"
     */
    public function testPropertyPreNom()
    {
    }

    /**
     * Test attribute "idRef"
     */
    public function testPropertyIdRef()
    {
    }

    /**
     * Test attribute "qualification"
     */
    public function testPropertyQualification()
    {
    }

    /**
     * Test attribute "nationalite"
     */
    public function testPropertyNationalite()
    {
    }

    /**
     * Test attribute "nomJF"
     */
    public function testPropertyNomJF()
    {
    }

    /**
     * Test attribute "dateNaissance"
     */
    public function testPropertyDateNaissance()
    {
    }

    /**
     * Test attribute "telephonePortable"
     */
    public function testPropertyTelephonePortable()
    {
    }

    /**
     * Test attribute "telephoneDomicile"
     */
    public function testPropertyTelephoneDomicile()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "web"
     */
    public function testPropertyWeb()
    {
    }

    /**
     * Test attribute "numVoie"
     */
    public function testPropertyNumVoie()
    {
    }

    /**
     * Test attribute "bisVoie"
     */
    public function testPropertyBisVoie()
    {
    }

    /**
     * Test attribute "nomVoie"
     */
    public function testPropertyNomVoie()
    {
    }

    /**
     * Test attribute "compVoie"
     */
    public function testPropertyCompVoie()
    {
    }

    /**
     * Test attribute "cP"
     */
    public function testPropertyCP()
    {
    }

    /**
     * Test attribute "commune"
     */
    public function testPropertyCommune()
    {
    }

    /**
     * Test attribute "numsecu"
     */
    public function testPropertyNumsecu()
    {
    }

    /**
     * Test attribute "numsecuCle"
     */
    public function testPropertyNumsecuCle()
    {
    }

    /**
     * Test attribute "lieuNaiss"
     */
    public function testPropertyLieuNaiss()
    {
    }

    /**
     * Test attribute "paysNaiss"
     */
    public function testPropertyPaysNaiss()
    {
    }

    /**
     * Test attribute "pays"
     */
    public function testPropertyPays()
    {
    }

    /**
     * Test attribute "commentaire"
     */
    public function testPropertyCommentaire()
    {
    }

    /**
     * Test attribute "modePaiement"
     */
    public function testPropertyModePaiement()
    {
    }

    /**
     * Test attribute "rIBEtablissement"
     */
    public function testPropertyRIBEtablissement()
    {
    }

    /**
     * Test attribute "rIBDomiciliation"
     */
    public function testPropertyRIBDomiciliation()
    {
    }

    /**
     * Test attribute "rIBTitulaire"
     */
    public function testPropertyRIBTitulaire()
    {
    }

    /**
     * Test attribute "rIBGuichet"
     */
    public function testPropertyRIBGuichet()
    {
    }

    /**
     * Test attribute "rIBCompte"
     */
    public function testPropertyRIBCompte()
    {
    }

    /**
     * Test attribute "rIBCle"
     */
    public function testPropertyRIBCle()
    {
    }

    /**
     * Test attribute "iBAN"
     */
    public function testPropertyIBAN()
    {
    }

    /**
     * Test attribute "bIC"
     */
    public function testPropertyBIC()
    {
    }

    /**
     * Test attribute "creePar"
     */
    public function testPropertyCreePar()
    {
    }

    /**
     * Test attribute "listeAgences"
     */
    public function testPropertyListeAgences()
    {
    }
}
