<?php
/**
 * ContractTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evolia
 *
 * Connection of Troops & Evolia
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Evolia;

/**
 * ContractTest Class Doc Comment
 *
 * @category    Class
 * @description Contract
 * @package     Evolia
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContractTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Contract"
     */
    public function testContract()
    {
    }

    /**
     * Test attribute "idContrat"
     */
    public function testPropertyIdContrat()
    {
    }

    /**
     * Test attribute "idPersonne"
     */
    public function testPropertyIdPersonne()
    {
    }

    /**
     * Test attribute "idClient"
     */
    public function testPropertyIdClient()
    {
    }

    /**
     * Test attribute "codeMission"
     */
    public function testPropertyCodeMission()
    {
    }

    /**
     * Test attribute "ordreClient"
     */
    public function testPropertyOrdreClient()
    {
    }

    /**
     * Test attribute "lieuxdeMission"
     */
    public function testPropertyLieuxdeMission()
    {
    }

    /**
     * Test attribute "rubriquesContractuelles"
     */
    public function testPropertyRubriquesContractuelles()
    {
    }

    /**
     * Test attribute "designation"
     */
    public function testPropertyDesignation()
    {
    }

    /**
     * Test attribute "adresse1"
     */
    public function testPropertyAdresse1()
    {
    }

    /**
     * Test attribute "adresse2"
     */
    public function testPropertyAdresse2()
    {
    }

    /**
     * Test attribute "adresse3"
     */
    public function testPropertyAdresse3()
    {
    }

    /**
     * Test attribute "cP"
     */
    public function testPropertyCP()
    {
    }

    /**
     * Test attribute "commune"
     */
    public function testPropertyCommune()
    {
    }

    /**
     * Test attribute "insee"
     */
    public function testPropertyInsee()
    {
    }

    /**
     * Test attribute "pays"
     */
    public function testPropertyPays()
    {
    }

    /**
     * Test attribute "telephone"
     */
    public function testPropertyTelephone()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "aPE"
     */
    public function testPropertyAPE()
    {
    }

    /**
     * Test attribute "tVAPays"
     */
    public function testPropertyTVAPays()
    {
    }

    /**
     * Test attribute "tVAClef"
     */
    public function testPropertyTVAClef()
    {
    }

    /**
     * Test attribute "sIREN"
     */
    public function testPropertySIREN()
    {
    }

    /**
     * Test attribute "nIC"
     */
    public function testPropertyNIC()
    {
    }

    /**
     * Test attribute "referenceAnalytique"
     */
    public function testPropertyReferenceAnalytique()
    {
    }

    /**
     * Test attribute "agence"
     */
    public function testPropertyAgence()
    {
    }

    /**
     * Test attribute "debut"
     */
    public function testPropertyDebut()
    {
    }

    /**
     * Test attribute "finPrevue"
     */
    public function testPropertyFinPrevue()
    {
    }

    /**
     * Test attribute "finReelle"
     */
    public function testPropertyFinReelle()
    {
    }

    /**
     * Test attribute "dateCreation"
     */
    public function testPropertyDateCreation()
    {
    }

    /**
     * Test attribute "categorieSalariale"
     */
    public function testPropertyCategorieSalariale()
    {
    }

    /**
     * Test attribute "motifEmbauche"
     */
    public function testPropertyMotifEmbauche()
    {
    }

    /**
     * Test attribute "justification"
     */
    public function testPropertyJustification()
    {
    }

    /**
     * Test attribute "missionARisqueL23131"
     */
    public function testPropertyMissionARisqueL23131()
    {
    }

    /**
     * Test attribute "finDeMission"
     */
    public function testPropertyFinDeMission()
    {
    }

    /**
     * Test attribute "heureDePresentation"
     */
    public function testPropertyHeureDePresentation()
    {
    }

    /**
     * Test attribute "contractOrder"
     */
    public function testPropertyContractOrder()
    {
    }

    /**
     * Test attribute "typeContrat"
     */
    public function testPropertyTypeContrat()
    {
    }

    /**
     * Test attribute "dateEffet"
     */
    public function testPropertyDateEffet()
    {
    }

    /**
     * Test attribute "dateFinAvenant"
     */
    public function testPropertyDateFinAvenant()
    {
    }

    /**
     * Test attribute "souplesseDebut"
     */
    public function testPropertySouplesseDebut()
    {
    }

    /**
     * Test attribute "souplesseFin"
     */
    public function testPropertySouplesseFin()
    {
    }

    /**
     * Test attribute "horairesParticulier"
     */
    public function testPropertyHorairesParticulier()
    {
    }

    /**
     * Test attribute "retourSignatureInterimaire"
     */
    public function testPropertyRetourSignatureInterimaire()
    {
    }

    /**
     * Test attribute "retourSignatureClient"
     */
    public function testPropertyRetourSignatureClient()
    {
    }

    /**
     * Test attribute "tauxPaye"
     */
    public function testPropertyTauxPaye()
    {
    }

    /**
     * Test attribute "tauxFacture"
     */
    public function testPropertyTauxFacture()
    {
    }

    /**
     * Test attribute "lotFacture"
     */
    public function testPropertyLotFacture()
    {
    }

    /**
     * Test attribute "dureeHebdo"
     */
    public function testPropertyDureeHebdo()
    {
    }

    /**
     * Test attribute "horaireCollectifMoyen"
     */
    public function testPropertyHoraireCollectifMoyen()
    {
    }

    /**
     * Test attribute "idMetier"
     */
    public function testPropertyIdMetier()
    {
    }

    /**
     * Test attribute "metier"
     */
    public function testPropertyMetier()
    {
    }

    /**
     * Test attribute "poste"
     */
    public function testPropertyPoste()
    {
    }

    /**
     * Test attribute "seuilEtDecompte"
     */
    public function testPropertySeuilEtDecompte()
    {
    }

    /**
     * Test attribute "salaireReference1"
     */
    public function testPropertySalaireReference1()
    {
    }

    /**
     * Test attribute "description1"
     */
    public function testPropertyDescription1()
    {
    }

    /**
     * Test attribute "risque1"
     */
    public function testPropertyRisque1()
    {
    }

    /**
     * Test attribute "moyenAcces"
     */
    public function testPropertyMoyenAcces()
    {
    }

    /**
     * Test attribute "periodeFermeture"
     */
    public function testPropertyPeriodeFermeture()
    {
    }

    /**
     * Test attribute "libelleMetier"
     */
    public function testPropertyLibelleMetier()
    {
    }

    /**
     * Test attribute "codePCS"
     */
    public function testPropertyCodePCS()
    {
    }
}
