<?php
/**
 * CustomerBillingAddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evolia
 *
 * Connection of Troops & Evolia
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Evolia;

/**
 * CustomerBillingAddressTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerBillingAddress
 * @package     Evolia
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerBillingAddressTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerBillingAddress"
     */
    public function testCustomerBillingAddress()
    {
    }

    /**
     * Test attribute "designation"
     */
    public function testPropertyDesignation()
    {
    }

    /**
     * Test attribute "adresse1"
     */
    public function testPropertyAdresse1()
    {
    }

    /**
     * Test attribute "adresse2"
     */
    public function testPropertyAdresse2()
    {
    }

    /**
     * Test attribute "adresse3"
     */
    public function testPropertyAdresse3()
    {
    }

    /**
     * Test attribute "cP"
     */
    public function testPropertyCP()
    {
    }

    /**
     * Test attribute "commune"
     */
    public function testPropertyCommune()
    {
    }

    /**
     * Test attribute "pays"
     */
    public function testPropertyPays()
    {
    }

    /**
     * Test attribute "telephone"
     */
    public function testPropertyTelephone()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "web"
     */
    public function testPropertyWeb()
    {
    }

    /**
     * Test attribute "aPE"
     */
    public function testPropertyAPE()
    {
    }

    /**
     * Test attribute "tVAClef"
     */
    public function testPropertyTVAClef()
    {
    }

    /**
     * Test attribute "tVAPays"
     */
    public function testPropertyTVAPays()
    {
    }

    /**
     * Test attribute "sIREN"
     */
    public function testPropertySIREN()
    {
    }

    /**
     * Test attribute "nIC"
     */
    public function testPropertyNIC()
    {
    }
}
