<?php
/**
 * PayrollViewModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evolia
 *
 * Connection of Troops & Evolia
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Evolia;

/**
 * PayrollViewModelTest Class Doc Comment
 *
 * @category    Class
 * @description PayrollViewModel
 * @package     Evolia
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PayrollViewModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PayrollViewModel"
     */
    public function testPayrollViewModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "startDate"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "endDate"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "candidate"
     */
    public function testPropertyCandidate()
    {
    }

    /**
     * Test attribute "documentUrl"
     */
    public function testPropertyDocumentUrl()
    {
    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {
    }
}
