<?php
/**
 * ReferencesResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evolia
 *
 * Connection of Troops & Evolia
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Evolia;

/**
 * ReferencesResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ReferencesResponse
 * @package     Evolia
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReferencesResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReferencesResponse"
     */
    public function testReferencesResponse()
    {
    }

    /**
     * Test attribute "bookkeepingVariables"
     */
    public function testPropertyBookkeepingVariables()
    {
    }

    /**
     * Test attribute "payrollItems"
     */
    public function testPropertyPayrollItems()
    {
    }

    /**
     * Test attribute "countries"
     */
    public function testPropertyCountries()
    {
    }

    /**
     * Test attribute "billingTerms"
     */
    public function testPropertyBillingTerms()
    {
    }

    /**
     * Test attribute "employeeStatuses"
     */
    public function testPropertyEmployeeStatuses()
    {
    }

    /**
     * Test attribute "nationalities"
     */
    public function testPropertyNationalities()
    {
    }

    /**
     * Test attribute "jobs"
     */
    public function testPropertyJobs()
    {
    }

    /**
     * Test attribute "legalReasons"
     */
    public function testPropertyLegalReasons()
    {
    }

    /**
     * Test attribute "vatRates"
     */
    public function testPropertyVatRates()
    {
    }
}
