<?php
/**
 * ReferenceItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evolia
 *
 * Connection of Troops & Evolia
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Evolia;

/**
 * ReferenceItemTest Class Doc Comment
 *
 * @category    Class
 * @description ReferenceItem
 * @package     Evolia
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReferenceItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReferenceItem"
     */
    public function testReferenceItem()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "billingTerm"
     */
    public function testPropertyBillingTerm()
    {
    }

    /**
     * Test attribute "iso"
     */
    public function testPropertyIso()
    {
    }

    /**
     * Test attribute "iso2"
     */
    public function testPropertyIso2()
    {
    }

    /**
     * Test attribute "iso3"
     */
    public function testPropertyIso3()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }
}
