<?php
/**
 * RubricValuesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evolia
 *
 * Connection of Troops & Evolia
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Evolia;

/**
 * RubricValuesTest Class Doc Comment
 *
 * @category    Class
 * @description RubricValues
 * @package     Evolia
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RubricValuesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RubricValues"
     */
    public function testRubricValues()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "libelle"
     */
    public function testPropertyLibelle()
    {
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
    }

    /**
     * Test attribute "commentaire"
     */
    public function testPropertyCommentaire()
    {
    }

    /**
     * Test attribute "basePayee"
     */
    public function testPropertyBasePayee()
    {
    }

    /**
     * Test attribute "tauxPayee"
     */
    public function testPropertyTauxPayee()
    {
    }

    /**
     * Test attribute "baseFacturee"
     */
    public function testPropertyBaseFacturee()
    {
    }

    /**
     * Test attribute "tauxFacturee"
     */
    public function testPropertyTauxFacturee()
    {
    }
}
