<?php
/**
 * SiretQueryResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evolia
 *
 * Connection of Troops & Evolia
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Evolia;

/**
 * SiretQueryResultTest Class Doc Comment
 *
 * @category    Class
 * @description SiretQueryResult
 * @package     Evolia
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SiretQueryResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SiretQueryResult"
     */
    public function testSiretQueryResult()
    {
    }

    /**
     * Test attribute "clientId"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "siteRef"
     */
    public function testPropertySiteRef()
    {
    }

    /**
     * Test attribute "companyName"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "registrationNumber"
     */
    public function testPropertyRegistrationNumber()
    {
    }

    /**
     * Test attribute "siteName"
     */
    public function testPropertySiteName()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "zipCode"
     */
    public function testPropertyZipCode()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }
}
