<?php
/**
 * TimeSheetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Evolia
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evolia
 *
 * Connection of Troops & Evolia
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Evolia;

/**
 * TimeSheetTest Class Doc Comment
 *
 * @category    Class
 * @description TimeSheet
 * @package     Evolia
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TimeSheetTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TimeSheet"
     */
    public function testTimeSheet()
    {
    }

    /**
     * Test attribute "contrat"
     */
    public function testPropertyContrat()
    {
    }

    /**
     * Test attribute "annee"
     */
    public function testPropertyAnnee()
    {
    }

    /**
     * Test attribute "semaine"
     */
    public function testPropertySemaine()
    {
    }

    /**
     * Test attribute "datePremierJourSemaine"
     */
    public function testPropertyDatePremierJourSemaine()
    {
    }

    /**
     * Test attribute "lundiJour"
     */
    public function testPropertyLundiJour()
    {
    }

    /**
     * Test attribute "lundiNuit"
     */
    public function testPropertyLundiNuit()
    {
    }

    /**
     * Test attribute "mardiJour"
     */
    public function testPropertyMardiJour()
    {
    }

    /**
     * Test attribute "mardiNuit"
     */
    public function testPropertyMardiNuit()
    {
    }

    /**
     * Test attribute "mercrediJour"
     */
    public function testPropertyMercrediJour()
    {
    }

    /**
     * Test attribute "mercrediNuit"
     */
    public function testPropertyMercrediNuit()
    {
    }

    /**
     * Test attribute "jeudiJour"
     */
    public function testPropertyJeudiJour()
    {
    }

    /**
     * Test attribute "jeudiNuit"
     */
    public function testPropertyJeudiNuit()
    {
    }

    /**
     * Test attribute "vendrediJour"
     */
    public function testPropertyVendrediJour()
    {
    }

    /**
     * Test attribute "vendrediNuit"
     */
    public function testPropertyVendrediNuit()
    {
    }

    /**
     * Test attribute "samediJour"
     */
    public function testPropertySamediJour()
    {
    }

    /**
     * Test attribute "samediNuit"
     */
    public function testPropertySamediNuit()
    {
    }

    /**
     * Test attribute "dimancheJour"
     */
    public function testPropertyDimancheJour()
    {
    }

    /**
     * Test attribute "dimancheNuit"
     */
    public function testPropertyDimancheNuit()
    {
    }

    /**
     * Test attribute "finDeMission"
     */
    public function testPropertyFinDeMission()
    {
    }

    /**
     * Test attribute "rubriquesVariables"
     */
    public function testPropertyRubriquesVariables()
    {
    }
}
